name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - '**'


env:
  PROJECT_ID: 'decent-core-438006-u1'
  SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
  CLUSTER_NAME: 'driver-pay-cluster' # TODO: update to your cluster name
  REGION: 'asia-south1' # TODO: update to your cluster zone
  REGISTRY_NAME: 'driver-pay' # TODO: update to your Artifact Registry docker repository name

jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    #    environment: 'production'

    steps:
      # Set up Node.js for Angular projects
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      # Build Java and Angular projects
      - name: Build Projects
        run: |
          SERVICE_NAMES= `driver-pay`
          echo "Service Names: $SERVICE_NAMES"
          npm install && npm test

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.GKE_PROJECT }}
          service_account_key: ${{ env.SERVICE_ACCOUNT_KEY }}

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.5.0
        with:
          credentials_json: ${{ env.SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker for Google Container Registry
        run: gcloud auth configure-docker

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      # Build the Docker image
      - name: Build and Push Docker Images
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          SERVICE_NAMES= 'driver-pay'
          echo "Service Names: $SERVICE_NAMES"
          echo "Building and pushing Docker image for $SERVICE_NAME"
          if [ -d "$SERVICE_NAME" ]; then
            cd $SERVICE_NAME
            IMAGE_NAME=gcr.io/decent-core-438006-u1/$SERVICE_NAME:$COMMIT_SHA
             docker build -t $IMAGE_NAME .
             docker push $IMAGE_NAME
             cd ..
           fi

      # Deploy the Docker image to the GKE cluster
      - name: Deploy to GKE
        run: |
          echo "Getting credentials for cluster $CLUSTER_NAME in zone $REGION"
          gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION --project $PROJECT_ID
          COMMIT_SHA=$(git rev-parse --short HEAD)
          SERVICE_NAMES='driver-pay'
          echo "Service Names: $SERVICE_NAMES"
          echo "Deploying $SERVICE_NAME to GKE"
          if [ -d "$SERVICE_NAME/k8s" ]; then
            sed -i "s|gcr.io/decent-core-438006-u1/$SERVICE_NAME:latest|gcr.io/decent-core-438006-u1/$SERVICE_NAME:$COMMIT_SHA|g" $SERVICE_NAME/k8s/deployment.yaml
            kubectl apply -f $SERVICE_NAME/k8s/
          fi
